/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2020-07-23 18:17:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp1;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.opentext.otds.as.ASConstants;
import com.opentext.otds.as.ASConstants;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1549390092584L));
    _jspx_dependants.put("/WEB-INF/jsp1/logo.jsp", Long.valueOf(1549390087490L));
    _jspx_dependants.put("/WEB-INF/jsp1/bottom.jsp", Long.valueOf(1549390087287L));
    _jspx_dependants.put("jar:file:/C:/OpenText/OTDS16.4.2/otdsws/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425993070000L));
    _jspx_dependants.put("jar:file:/C:/OpenText/OTDS16.4.2/otdsws/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425993070000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.opentext.otds.as.ASConstants");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fbasename_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fparam;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fbasename_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fparam = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fbasename_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey.release();
    _005fjspx_005ftagPool_005ffmt_005fparam.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.opentext.otds.as.UserBean user = null;
      user = (com.opentext.otds.as.UserBean) _jspx_page_context.getAttribute("user", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (user == null){
        user = new com.opentext.otds.as.UserBean();
        _jspx_page_context.setAttribute("user", user, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("user"), request);
      out.write('\r');
      out.write('\n');
      //  fmt:setLocale
      org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag _jspx_th_fmt_005fsetLocale_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag) _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag.class);
      boolean _jspx_th_fmt_005fsetLocale_005f0_reused = false;
      try {
        _jspx_th_fmt_005fsetLocale_005f0.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fsetLocale_005f0.setParent(null);
        // /WEB-INF/jsp1/login.jsp(6,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fsetLocale_005f0.setValue(request.getAttribute(ASConstants.JSPLANG));
        int _jspx_eval_fmt_005fsetLocale_005f0 = _jspx_th_fmt_005fsetLocale_005f0.doStartTag();
        if (_jspx_th_fmt_005fsetLocale_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
        _jspx_th_fmt_005fsetLocale_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fsetLocale_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fsetLocale_005f0_reused);
      }
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_fmt_005fsetBundle_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_fmt_005fsetBundle_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
String otds_build = (String)request.getAttribute(ASConstants.OTDS_BUILD);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"");
      out.print(request.getAttribute(ASConstants.JSPLANG));
      out.write("\">\r\n");
      out.write("\t<head>\r\n");
      out.write("        ");

        boolean isTwoStepLogin = Boolean.parseBoolean((String)request.getAttribute("twosteplogin"));        
        String otds_username = String.valueOf(user.getUserId());
        boolean hasError = request.getAttribute("error") != null;

        boolean isFirstStep = isTwoStepLogin && otds_username.isEmpty();
        boolean isSecondStep = isTwoStepLogin && !isFirstStep;

        String usernameautofocus = otds_username.isEmpty() ? "autofocus" : "";
        String passwordautofocus = (isSecondStep || !otds_username.isEmpty()) ? "autofocus" : "";

        String rfaParam = null;
        String rfaHTML = null;
        if (request.getAttribute(ASConstants.PARAM_OTDS_RFA) != null) {
          rfaHTML = String.valueOf(org.apache.commons.lang3.StringEscapeUtils.escapeHtml3(String.valueOf(request.getAttribute(ASConstants.PARAM_OTDS_RFA))));
          rfaParam = java.net.URLEncoder.encode((String)request.getAttribute(ASConstants.PARAM_OTDS_RFA), "UTF-8");
        }
        String pwresetLink = "login?pwreset";
        String signupLink = "login?signup";
        String backLink = "login?logbackin";
        String cancelLink = "login?cancel";
        if (rfaParam != null) {
          pwresetLink += "&RFA="+rfaParam;
          signupLink += "&RFA="+rfaParam;
          backLink += "&RFA="+rfaParam;
          cancelLink += "&RFA="+rfaParam;
        }
        
        String loginButtonStr = request.getAttribute("signcontext") != null ? "prompt.approve" : "prompt.login.button";
        
      out.write("\r\n");
      out.write("        <title>");
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./login1/login.css?v=");
      out.print(otds_build);
      out.write("\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./login1/login_custom.css?v=");
      out.print(otds_build);
      out.write("\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"./app_directory_services.ico\">\r\n");
      out.write("        <script src=\"./jquery.min.js?v=");
      out.print(otds_build);
      out.write("\"></script>\r\n");
      out.write("        <script src=\"./login1/scripts.js?v=");
      out.print(otds_build);
      out.write("\"></script>\r\n");
      out.write("        <script src=\"./login1/login.js?v=");
      out.print(otds_build);
      out.write("\"></script>\r\n");
      out.write("        ");
 if (isTwoStepLogin && isSecondStep) { 
      out.write("\r\n");
      out.write("        <script src=\"./login1/login_step2.js?v=");
      out.print(otds_build);
      out.write("\"></script>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        ");
 if (request.getAttribute("recaptcha_public") != null) { 
      out.write("\r\n");
      out.write("            <script src=\"https://www.google.com/recaptcha/api.js\" async defer></script>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td>\r\n");
      out.write("        <div id=\"signin-wrapper\">\r\n");
      out.write("            <div id=\"signin-wrapper-inner\">\r\n");
      out.write("                <div id=\"signin-top\">\r\n");
      out.write("                    ");

String headerImg = String.valueOf(request.getAttribute(ASConstants.PARAM_OTDS_HEADER_STYLE));
if (!headerImg.matches(".+[.].+")) {
    headerImg+=".png";
}
String headerImgSrc = "./login1/"+String.valueOf(org.apache.commons.lang3.StringEscapeUtils.escapeHtml3(headerImg));

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("                    <div id=\"logo-holder\"><img src=\"");
      out.print(headerImgSrc);
      out.write("\" id=\"ot-logo\"></div>\r\n");
      out.write("                    <div id=\"signin-branding\">\r\n");
      out.write("                        <div id=\"signin\">\r\n");
      out.write("                            <form method=\"POST\" action=\"login\" id=\"thisform\">\r\n");
      out.write("                                \r\n");
      out.write("                                <input type=\"hidden\" name=\"fragment\" id=\"fragment\">\r\n");
      out.write("                                \r\n");
      out.write("\t\t\t\t\t\t\t\t");
 if (request.getAttribute(ASConstants.PARAM_OTDS_RFA) != null) { 
      out.write("\r\n");
      out.write("                                <input type=\"hidden\" name=\"");
      out.print( ASConstants.PARAM_OTDS_RFA );
      out.write("\" value=\"");
      out.print(rfaHTML);
      out.write("\">\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                                ");
 if (request.getAttribute(ASConstants.PARAM_OTDS_AUTH) != null) { 
      out.write("\r\n");
      out.write("                                    <input type=\"hidden\" name=\"");
      out.print( ASConstants.PARAM_OTDS_AUTH );
      out.write("\" value=\"");
      out.print(String.valueOf(org.apache.commons.lang3.StringEscapeUtils.escapeHtml3(String.valueOf(request.getAttribute(ASConstants.PARAM_OTDS_AUTH)))));
      out.write("\">\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                                <input type=\"hidden\" name=\"");
      out.print( ASConstants.PARAM_OTDS_CSRF);
      out.write("\" value=\"");
      out.print(request.getAttribute(ASConstants.PARAM_OTDS_CSRF));
      out.write("\">\r\n");
      out.write("                                \r\n");
      out.write("                                <fieldset>\r\n");
      out.write("                                <table border=\"0\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    ");
 if (request.getAttribute("signcontext") != null) { 
      out.write("\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td class=\"prompts\"></td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                            <span role=\"alert\">\r\n");
      out.write("                                            ");
      if (_jspx_meth_fmt_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    ");
 } else { 
      out.write("\r\n");
      out.write("                                    ");
 String login_msg = (String)request.getAttribute("loginmessage"); 
      out.write("\r\n");
      out.write("                                    ");
 if (login_msg != null) { 
      out.write("\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td class=\"prompts\"></td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                            <span role=\"alert\">\r\n");
      out.write("                                            ");
 if (login_msg.startsWith("prompt.")) { 
      out.write("\r\n");
      out.write("                                                ");
      //  fmt:message
      org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
      boolean _jspx_th_fmt_005fmessage_005f2_reused = false;
      try {
        _jspx_th_fmt_005fmessage_005f2.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fmessage_005f2.setParent(null);
        // /WEB-INF/jsp1/login.jsp(105,48) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fmessage_005f2.setKey(login_msg);
        // /WEB-INF/jsp1/login.jsp(105,48) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fmessage_005f2.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${custom}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        int _jspx_eval_fmt_005fmessage_005f2 = _jspx_th_fmt_005fmessage_005f2.doStartTag();
        if (_jspx_th_fmt_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
        _jspx_th_fmt_005fmessage_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f2_reused);
      }
      out.write("\r\n");
      out.write("                                            ");
 } else { 
      out.write("\r\n");
      out.write("                                                ");
      out.print(login_msg);
      out.write("\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"prompts\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
 String key = (String)request.getAttribute("error"); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
 if (key == null || key.trim().length() == 0) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
 key = "failed.login.msg"; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"error\" role=\"alert\"><img src=\"./login1/notification_validation_error16.png\" alt=\"\">&nbsp;&nbsp;");
      //  fmt:message
      org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
      boolean _jspx_th_fmt_005fmessage_005f3_reused = false;
      try {
        _jspx_th_fmt_005fmessage_005f3.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fmessage_005f3.setParent(null);
        // /WEB-INF/jsp1/login.jsp(122,117) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fmessage_005f3.setKey(key);
        int _jspx_eval_fmt_005fmessage_005f3 = _jspx_th_fmt_005fmessage_005f3.doStartTag();
        if (_jspx_th_fmt_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
        _jspx_th_fmt_005fmessage_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f3_reused);
      }
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 if (request.getAttribute("info") != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"info\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      //  fmt:message
      org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
      boolean _jspx_th_fmt_005fmessage_005f4_reused = false;
      try {
        _jspx_th_fmt_005fmessage_005f4.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fmessage_005f4.setParent(null);
        // /WEB-INF/jsp1/login.jsp(126,13) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fmessage_005f4.setKey((String)request.getAttribute("info"));
        int _jspx_eval_fmt_005fmessage_005f4 = _jspx_th_fmt_005fmessage_005f4.doStartTag();
        if (_jspx_eval_fmt_005fmessage_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_fmt_005fmessage_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fmessage_005f4);
          }
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 if (request.getAttribute("info").equals("otds.info.linkaccount")) { 
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            //  fmt:param
            org.apache.taglibs.standard.tag.rt.fmt.ParamTag _jspx_th_fmt_005fparam_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.ParamTag) _005fjspx_005ftagPool_005ffmt_005fparam.get(org.apache.taglibs.standard.tag.rt.fmt.ParamTag.class);
            boolean _jspx_th_fmt_005fparam_005f0_reused = false;
            try {
              _jspx_th_fmt_005fparam_005f0.setPageContext(_jspx_page_context);
              _jspx_th_fmt_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fmessage_005f4);
              int _jspx_eval_fmt_005fparam_005f0 = _jspx_th_fmt_005fparam_005f0.doStartTag();
              if (_jspx_eval_fmt_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                if (_jspx_eval_fmt_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fparam_005f0);
                }
                do {
                  out.print(request.getAttribute(ASConstants.PARAM_OTDS_AUTHPROVIDER));
                  int evalDoAfterBody = _jspx_th_fmt_005fparam_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_fmt_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                }
              }
              if (_jspx_th_fmt_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005ffmt_005fparam.reuse(_jspx_th_fmt_005fparam_005f0);
              _jspx_th_fmt_005fparam_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fparam_005f0_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 } 
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_fmt_005fmessage_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_fmt_005fmessage_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_fmt_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey.reuse(_jspx_th_fmt_005fmessage_005f4);
        _jspx_th_fmt_005fmessage_005f4_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f4, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f4_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 if (request.getAttribute("instruction") != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"instruction\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      //  fmt:message
      org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f5 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
      boolean _jspx_th_fmt_005fmessage_005f5_reused = false;
      try {
        _jspx_th_fmt_005fmessage_005f5.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fmessage_005f5.setParent(null);
        // /WEB-INF/jsp1/login.jsp(135,13) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fmessage_005f5.setKey((String)request.getAttribute("instruction"));
        int _jspx_eval_fmt_005fmessage_005f5 = _jspx_th_fmt_005fmessage_005f5.doStartTag();
        if (_jspx_eval_fmt_005fmessage_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_fmt_005fmessage_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fmessage_005f5);
          }
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 if (request.getAttribute("instruction").equals("otds.info.continueto")) { 
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
            //  fmt:param
            org.apache.taglibs.standard.tag.rt.fmt.ParamTag _jspx_th_fmt_005fparam_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.ParamTag) _005fjspx_005ftagPool_005ffmt_005fparam.get(org.apache.taglibs.standard.tag.rt.fmt.ParamTag.class);
            boolean _jspx_th_fmt_005fparam_005f1_reused = false;
            try {
              _jspx_th_fmt_005fparam_005f1.setPageContext(_jspx_page_context);
              _jspx_th_fmt_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fmessage_005f5);
              int _jspx_eval_fmt_005fparam_005f1 = _jspx_th_fmt_005fparam_005f1.doStartTag();
              if (_jspx_eval_fmt_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                if (_jspx_eval_fmt_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fparam_005f1);
                }
                do {
                  out.print(request.getAttribute(ASConstants.PARAM_OTDS_RESOURCE_NAME));
                  int evalDoAfterBody = _jspx_th_fmt_005fparam_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_fmt_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                }
              }
              if (_jspx_th_fmt_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005ffmt_005fparam.reuse(_jspx_th_fmt_005fparam_005f1);
              _jspx_th_fmt_005fparam_005f1_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fparam_005f1_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 } 
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_fmt_005fmessage_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_fmt_005fmessage_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_fmt_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey.reuse(_jspx_th_fmt_005fmessage_005f5);
        _jspx_th_fmt_005fmessage_005f5_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f5, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f5_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 if (request.getAttribute("systemError") != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"error\" role=\"alert\"><img src=\"./login1/notification_validation_error16.png\" alt=\"\">&nbsp;&nbsp;");
      if (_jspx_meth_fmt_005fmessage_005f6(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td class=\"prompts\"></td>\r\n");
      out.write("                                        <td><div id=\"signin-label\"><span class=\"fieldlabel\"><label for=\"otds_username\">");
      if (_jspx_meth_fmt_005fmessage_005f7(_jspx_page_context))
        return;
      out.write("</label></span></div></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td class=\"prompts\"></td>\r\n");
      out.write("                                        <td><div id=\"signin-input\"><input class=\"field-form-input\" type=\"text\" ");
      out.print(usernameautofocus);
      out.write(" id=\"otds_username\" name=\"otds_username\"\r\n");
      out.write("                                        value=\"");
      out.print( String.valueOf(org.apache.commons.lang3.StringEscapeUtils.escapeHtml3(otds_username)) );
      out.write("\"></div></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    \r\n");
      out.write("                                    ");
 if (!isTwoStepLogin || isSecondStep) { 
      out.write("\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td class=\"prompts\"></td>\r\n");
      out.write("                                            <td><div id=\"signin-label\"><span class=\"fieldlabel\"><label for=\"otds_password\">");
      if (_jspx_meth_fmt_005fmessage_005f8(_jspx_page_context))
        return;
      out.write("</label></span></div></td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td class=\"prompts\"></td>\r\n");
      out.write("                                            <td><div id=\"signin-input\"><input class=\"field-form-input\" type=\"password\" id=\"otds_password\" name=\"otds_password\" \r\n");
      out.write("                                              ");
      out.print(passwordautofocus);
      out.write(" autocomplete=\"off\" value=\"\"></div></td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        \r\n");
      out.write("                                        ");
 if (request.getAttribute("recaptcha_public") != null) { 
      out.write("\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td class=\"prompts\"></td>\r\n");
      out.write("                                            <td>&nbsp;</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td class=\"prompts\"></td>\r\n");
      out.write("                                            <td><div class=\"g-recaptcha\" data-sitekey=\"");
      out.print(request.getAttribute("recaptcha_public"));
      out.write("\"></div></td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"prompts\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"signin-submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" id=\"loginbutton\" \r\n");
      out.write("                                                \r\n");
      out.write("                                                ");
 if (isTwoStepLogin && isFirstStep) { 
      out.write("\r\n");
      out.write("                                                  value=\"");
      if (_jspx_meth_fmt_005fmessage_005f9(_jspx_page_context))
        return;
      out.write("\" \r\n");
      out.write("                                                ");
 } else { 
      out.write("\r\n");
      out.write("                                                  value=\"");
      //  fmt:message
      org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f10 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
      boolean _jspx_th_fmt_005fmessage_005f10_reused = false;
      try {
        _jspx_th_fmt_005fmessage_005f10.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fmessage_005f10.setParent(null);
        // /WEB-INF/jsp1/login.jsp(189,57) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fmessage_005f10.setKey(loginButtonStr);
        int _jspx_eval_fmt_005fmessage_005f10 = _jspx_th_fmt_005fmessage_005f10.doStartTag();
        if (_jspx_th_fmt_005fmessage_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f10);
        _jspx_th_fmt_005fmessage_005f10_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f10, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f10_reused);
      }
      out.write("\" \r\n");
      out.write("                                                ");
 } 
      out.write("\r\n");
      out.write("                                                \r\n");
      out.write("                                                class=\"button\"\r\n");
      out.write("                                            >\r\n");
      out.write("                                            \r\n");
      out.write("                                            ");
 if (request.getAttribute("signcontext") != null) { 
      out.write("\r\n");
      out.write("                                                <input type=\"button\" id=\"cancelbutton\" class=\"button\" data-href=\"");
      out.print(cancelLink);
      out.write("\" value=\"");
      if (_jspx_meth_fmt_005fmessage_005f11(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                            \r\n");
      out.write("                                            <span id=\"signin-links\">\r\n");
      out.write("                                            \r\n");
      out.write("                                            ");
 if (isTwoStepLogin && isSecondStep) { 
      out.write("\r\n");
      out.write("                                                <a id=\"backLink\" href=\"");
      out.print(backLink);
      out.write('"');
      out.write('>');
      if (_jspx_meth_fmt_005fmessage_005f12(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                            ");
 if (request.getAttribute("passwordresetenabled") != null) { 
      out.write("\r\n");
      out.write("                                                <a href=\"");
      out.print(pwresetLink);
      out.write('"');
      out.write('>');
      if (_jspx_meth_fmt_005fmessage_005f13(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                            ");
 if (request.getAttribute("selfprovisioningenabled") != null) { 
      out.write("\r\n");
      out.write("                                                <a href=\"");
      out.print(signupLink);
      out.write('"');
      out.write('>');
      if (_jspx_meth_fmt_005fmessage_005f14(_jspx_page_context))
        return;
      out.write("</a>\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                            </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    \r\n");
      out.write("                                    ");
 if (!isTwoStepLogin || isFirstStep) { 
      out.write("\r\n");
      out.write("                                        ");
 if (request.getAttribute(ASConstants.PARAM_OTDS_AUTHPROVIDER+"0") != null) { 
      out.write("\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                            <td class=\"prompts\"></td>\r\n");
      out.write("                                            <td>&nbsp;<input type=\"hidden\" name=\"");
      out.print(ASConstants.PARAM_OTDS_AUTHPROVIDER);
      out.write("\" id=\"");
      out.print(ASConstants.PARAM_OTDS_AUTHPROVIDER);
      out.write("\"></td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                            <td></td>\r\n");
      out.write("                                            <td>&nbsp;</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <div id=\"signin-with-label\">");
      if (_jspx_meth_fmt_005fmessage_005f15(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    ");
 int numAuthProviders=0; 
      out.write("\r\n");
      out.write("                                                    ");
 for (int i=0;;i++) { 
      out.write("\r\n");
      out.write("                                                        ");
 String authprovider = (String)request.getAttribute(ASConstants.PARAM_OTDS_AUTHPROVIDER+i);
      out.write("\r\n");
      out.write("                                                        ");
 String authproviderimage = (String)request.getAttribute(ASConstants.PARAM_OTDS_AUTHPROVIDERIMAGE+i);
      out.write("\r\n");
      out.write("                                                        ");
 String authprovidercustomimage = (String)request.getAttribute(ASConstants.PARAM_OTDS_AUTHPROVIDERCUSTOMIMAGE+i);
      out.write("\r\n");
      out.write("                                                        ");
 if (authprovider == null) break; 
      out.write("\r\n");
      out.write("                                                        ");
 if (authproviderimage != null && !authproviderimage.isEmpty()) { 
      out.write("\r\n");
      out.write("                                                            <input type=\"submit\" value=\"\" class=\"authproviderbtn ");
      out.print(authproviderimage);
      out.write("\" style=\"margin-right:0.5em;\" data-authprovider=\"");
      out.print(authprovider);
      out.write("\" alt=\"");
      out.print(authprovider);
      out.write("\">\r\n");
      out.write("                                                            ");
numAuthProviders++;
      out.write("\r\n");
      out.write("                                                        ");
 } else if(authprovidercustomimage != null && !authprovidercustomimage.isEmpty()) { 
      out.write("\r\n");
      out.write("                                                            <input type=\"submit\" value=\"\" class=\"authproviderbtn third_party_custom\" style=\"background-image:url('./login1/");
      out.print(authprovidercustomimage);
      out.write("'); margin-right:0.5em;\" data-authprovider=\"");
      out.print(authprovider);
      out.write("\" alt=\"");
      out.print(authprovider);
      out.write("\">\r\n");
      out.write("                                                            ");
numAuthProviders++;
      out.write("\r\n");
      out.write("                                                        ");
 } 
      out.write("\r\n");
      out.write("                                                    ");
 } 
      out.write("\r\n");
      out.write("                                                    \r\n");
      out.write("                                                    <span class=\"dropdown\" ");
if (numAuthProviders == 0) {
      out.write(" style=\"position: relative\" ");
}
      out.write(" >\r\n");
      out.write("                                                    <button type=\"button\" id=\"moreProviders\" class=\"button_secondary\" style=\"padding-left:0.5em;margin-top:0.2em;\">\r\n");
      out.write("                                                    ");
      if (_jspx_meth_fmt_005fmessage_005f16(_jspx_page_context))
        return;
      out.write("<span class=\"more-button-icon-secondary\"></span>\r\n");
      out.write("                                                    </button>\r\n");
      out.write("                                                    <ul class=\"secondary-menu\" id=\"moreProvidersList\" style=\"min-width:100px;\">\r\n");
      out.write("                                                    ");
 for (int i=0;;i++) { 
      out.write("\r\n");
      out.write("                                                        ");
 String authprovider = (String)request.getAttribute(ASConstants.PARAM_OTDS_AUTHPROVIDER+i);
      out.write("\r\n");
      out.write("                                                        ");
 if (authprovider == null) break; 
      out.write("\r\n");
      out.write("                                                        <li class=\"secondary-menu-item authprovider-choice\" data-authprovider=\"");
      out.print(authprovider);
      out.write("\" tabindex=\"0\">\r\n");
      out.write("                                                            <div style=\"padding-left: 0.5em;\">\r\n");
      out.write("                                                                ");
      out.print(authprovider);
      out.write("\r\n");
      out.write("                                                                <div class=\"divider-h\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                    ");
 } 
      out.write("\r\n");
      out.write("                                                    </ul>\r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                                </table>\r\n");
      out.write("                                </fieldset>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"signin-wrapper-bottom\">\r\n");
      out.write("    <div id=\"signin-bottom\">\r\n");
      out.write("        ");

        java.util.Map<String,String> langs=(java.util.Map<String,String>)request.getAttribute(ASConstants.LANGSMAP);
        
        if (request.getAttribute(ASConstants.OTDSLANG) == null) {
            request.setAttribute(ASConstants.OTDSLANG, "en");
        }
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div id=\"signin-footer\">\r\n");
      out.write("            <span></span>\r\n");
      out.write("            ");
 if ("true".equals(request.getAttribute(ASConstants.SHOWLANGS))) { 
      out.write("\r\n");
      out.write("                <span class=\"dropdown\" style=\"margin-left:-175px;\">\r\n");
      out.write("                <button type=\"button\" id=\"langsButton\" class=\"button_secondary\" style=\"padding-left:0.5em;\">\r\n");
      out.write("                <span class=\"language-button-icon\"></span>");
      out.print(langs.get(request.getAttribute(ASConstants.OTDSLANG)));
      out.write("<span class=\"more-button-icon-secondary\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                ");
Integer shiftLangs = -10*langs.size();
      out.write("\r\n");
      out.write("                <ul class=\"secondary-menu\" id=\"langsList\" style=\"min-width:100px;bottom:");
      out.print(shiftLangs.toString());
      out.write("px;\">\r\n");
      out.write("                ");
 for (java.util.Map.Entry<String,String> lang : langs.entrySet()) { 
      out.write("\r\n");
      out.write("                    <li class=\"secondary-menu-item lang-choice\" data-lang=\"");
      out.print(lang.getKey());
      out.write("\" tabindex=\"0\">\r\n");
      out.write("                        <div style=\"padding-left: 0.5em;\" lang=\"");
      out.print(lang.getKey());
      out.write("\">\r\n");
      out.write("                            ");
      out.print(lang.getValue());
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t\t<div class=\"divider-h\"></div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("                </span>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <span id=\"copyright\">\r\n");
      out.write("            ");
      //  fmt:message
      org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f17 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
      boolean _jspx_th_fmt_005fmessage_005f17_reused = false;
      try {
        _jspx_th_fmt_005fmessage_005f17.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fmessage_005f17.setParent(null);
        // /WEB-INF/jsp1/bottom.jsp(35,12) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fmessage_005f17.setKey("copyright");
        int _jspx_eval_fmt_005fmessage_005f17 = _jspx_th_fmt_005fmessage_005f17.doStartTag();
        if (_jspx_eval_fmt_005fmessage_005f17 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_fmt_005fmessage_005f17 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fmessage_005f17);
          }
          do {
            out.write("\r\n");
            out.write("                ");
            //  fmt:param
            org.apache.taglibs.standard.tag.rt.fmt.ParamTag _jspx_th_fmt_005fparam_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.ParamTag) _005fjspx_005ftagPool_005ffmt_005fparam.get(org.apache.taglibs.standard.tag.rt.fmt.ParamTag.class);
            boolean _jspx_th_fmt_005fparam_005f2_reused = false;
            try {
              _jspx_th_fmt_005fparam_005f2.setPageContext(_jspx_page_context);
              _jspx_th_fmt_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fmessage_005f17);
              int _jspx_eval_fmt_005fparam_005f2 = _jspx_th_fmt_005fparam_005f2.doStartTag();
              if (_jspx_eval_fmt_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                if (_jspx_eval_fmt_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fparam_005f2);
                }
                do {
                  out.print(String.valueOf(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR)));
                  int evalDoAfterBody = _jspx_th_fmt_005fparam_005f2.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_fmt_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                }
              }
              if (_jspx_th_fmt_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005ffmt_005fparam.reuse(_jspx_th_fmt_005fparam_005f2);
              _jspx_th_fmt_005fparam_005f2_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fparam_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fparam_005f2_reused);
            }
            out.write("\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_fmt_005fmessage_005f17.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_fmt_005fmessage_005f17 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_fmt_005fmessage_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey.reuse(_jspx_th_fmt_005fmessage_005f17);
        _jspx_th_fmt_005fmessage_005f17_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f17, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f17_reused);
      }
      out.write("\r\n");
      out.write("            </span>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fsetBundle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setBundle
    org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag _jspx_th_fmt_005fsetBundle_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag) _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fbasename_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag.class);
    boolean _jspx_th_fmt_005fsetBundle_005f0_reused = false;
    try {
      _jspx_th_fmt_005fsetBundle_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fsetBundle_005f0.setParent(null);
      // /WEB-INF/jsp1/login.jsp(7,0) name = basename type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fsetBundle_005f0.setBasename("login");
      int _jspx_eval_fmt_005fsetBundle_005f0 = _jspx_th_fmt_005fsetBundle_005f0.doStartTag();
      if (_jspx_th_fmt_005fsetBundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f0);
      _jspx_th_fmt_005fsetBundle_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fsetBundle_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fsetBundle_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fsetBundle_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setBundle
    org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag _jspx_th_fmt_005fsetBundle_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag) _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag.class);
    boolean _jspx_th_fmt_005fsetBundle_005f1_reused = false;
    try {
      _jspx_th_fmt_005fsetBundle_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fsetBundle_005f1.setParent(null);
      // /WEB-INF/jsp1/login.jsp(8,0) name = basename type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fsetBundle_005f1.setBasename("login_custom");
      // /WEB-INF/jsp1/login.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fsetBundle_005f1.setVar("custom");
      int _jspx_eval_fmt_005fsetBundle_005f1 = _jspx_th_fmt_005fsetBundle_005f1.doStartTag();
      if (_jspx_th_fmt_005fsetBundle_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f1);
      _jspx_th_fmt_005fsetBundle_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fsetBundle_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fsetBundle_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f0_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f0.setParent(null);
      // /WEB-INF/jsp1/login.jsp(44,15) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f0.setKey("page.title");
      int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      _jspx_th_fmt_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f1_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f1.setParent(null);
      // /WEB-INF/jsp1/login.jsp(93,44) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f1.setKey("prompt.esign");
      int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
      _jspx_th_fmt_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f6 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f6_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f6.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f6.setParent(null);
      // /WEB-INF/jsp1/login.jsp(143,117) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f6.setKey("otds.as.systemFailure");
      int _jspx_eval_fmt_005fmessage_005f6 = _jspx_th_fmt_005fmessage_005f6.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f6);
      _jspx_th_fmt_005fmessage_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f6, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f7 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f7_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f7.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f7.setParent(null);
      // /WEB-INF/jsp1/login.jsp(150,119) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f7.setKey("prompt.username");
      int _jspx_eval_fmt_005fmessage_005f7 = _jspx_th_fmt_005fmessage_005f7.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f7);
      _jspx_th_fmt_005fmessage_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f7, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f8 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f8_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f8.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f8.setParent(null);
      // /WEB-INF/jsp1/login.jsp(161,123) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f8.setKey("prompt.password");
      int _jspx_eval_fmt_005fmessage_005f8 = _jspx_th_fmt_005fmessage_005f8.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f8);
      _jspx_th_fmt_005fmessage_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f8, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f9 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f9_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f9.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f9.setParent(null);
      // /WEB-INF/jsp1/login.jsp(187,57) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f9.setKey("prompt.next.button");
      int _jspx_eval_fmt_005fmessage_005f9 = _jspx_th_fmt_005fmessage_005f9.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f9);
      _jspx_th_fmt_005fmessage_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f9, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f11 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f11_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f11.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f11.setParent(null);
      // /WEB-INF/jsp1/login.jsp(196,137) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f11.setKey("prompt.cancel");
      int _jspx_eval_fmt_005fmessage_005f11 = _jspx_th_fmt_005fmessage_005f11.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f11);
      _jspx_th_fmt_005fmessage_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f11, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f12 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f12_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f12.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f12.setParent(null);
      // /WEB-INF/jsp1/login.jsp(202,86) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f12.setKey("prompt.back");
      int _jspx_eval_fmt_005fmessage_005f12 = _jspx_th_fmt_005fmessage_005f12.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f12);
      _jspx_th_fmt_005fmessage_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f12, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f13 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f13_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f13.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f13.setParent(null);
      // /WEB-INF/jsp1/login.jsp(205,75) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f13.setKey("prompt.forgotpassword");
      int _jspx_eval_fmt_005fmessage_005f13 = _jspx_th_fmt_005fmessage_005f13.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f13);
      _jspx_th_fmt_005fmessage_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f13, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f14 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f14_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f14.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f14.setParent(null);
      // /WEB-INF/jsp1/login.jsp(208,74) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f14.setKey("prompt.createaccount");
      int _jspx_eval_fmt_005fmessage_005f14 = _jspx_th_fmt_005fmessage_005f14.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f14);
      _jspx_th_fmt_005fmessage_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f14, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f15 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f15_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f15.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f15.setParent(null);
      // /WEB-INF/jsp1/login.jsp(227,80) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f15.setKey("prompt.authprovider");
      int _jspx_eval_fmt_005fmessage_005f15 = _jspx_th_fmt_005fmessage_005f15.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f15);
      _jspx_th_fmt_005fmessage_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f15, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f15_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f16 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f16_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f16.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f16.setParent(null);
      // /WEB-INF/jsp1/login.jsp(247,52) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f16.setKey("prompt.otherprovider");
      int _jspx_eval_fmt_005fmessage_005f16 = _jspx_th_fmt_005fmessage_005f16.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f16);
      _jspx_th_fmt_005fmessage_005f16_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f16, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f16_reused);
    }
    return false;
  }
}
